---
- hosts: gcp
  tasks:
    - name: Install k8s related packages
      snap:
        name: "{{ packages }}"
        classic: yes
      vars:
        packages:
          - kubectl
      become: yes
    # This task may be failed if MachineType if f1-micro.
    # In that case, please change MachineType to g1-small.
    - name: Install kustomize
      command: /bin/bash -lc "go get -v sigs.k8s.io/kustomize/cmd/kustomize"
      register: result
      # verbose log of 'go get' is written not in stdout, but in stderr.
      changed_when: "'(download)' in result.stderr"
    - name: Add completion settings of GCP CLI
      blockinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        block: |
          # The next line updates PATH for the Google Cloud SDK.
          . /snap/google-cloud-sdk/current/path.bash.inc
          # The next line enables shell command completion for gcloud.
          . /snap/google-cloud-sdk/current/completion.bash.inc
        marker_begin: "gcloud settings: BEGIN"
        marker_end: "gcloud settings: END"
        create: yes
    - name: Setup settings related to VPN
      import_tasks: openvpn.yml
