---
- hosts: gcp
  tasks:
    - name: Install k8s related packages
      snap:
        name: "{{ packages }}"
        classic: yes
      vars:
        packages:
          - kubectl
      become: yes
    - name: Add completion settings of GCP CLI
      block:
        - name: Install bash completion libraries to resolve dependencies of GCP CLI
          apt:
            name: bash-completion
            update_cache: yes
            cache_valid_time: 3600
            install_recommends: no
          become: yes
        - name: Check whether kubectl completion file exists
          stat:
            path: /etc/bash_completion.d/kubectl
          register: result
        - name: Create kubectl completion file
          command: /bin/bash -lc  "kubectl completion bash > /etc/bash_completion.d/kubectl"
          when: not result.stat.exists
          become: yes
    - name: Setup settings related to VPN
      import_tasks: openvpn.yml
