---
- hosts: gcp
  tasks:
    - name: Install k8s related packages
      snap:
        name: "{{ packages }}"
        classic: yes
      vars:
        packages:
          - kubectl
      become: yes
    # This task may be failed if MachineType if f1-micro.
    # In that case, please change MachineType to g1-small.
    - name: Install kustomize
      command: /bin/bash -lc "go get -v sigs.k8s.io/kustomize/cmd/kustomize"
      register: result
      # verbose log of 'go get' is written not in stdout, but in stderr.
      changed_when: "'(download)' in result.stderr"
    - name: Add completion settings of GCP CLI
      block:
        - name: Install bash completion libraries to resolve dependencies of GCP CLI
          apt:
            name: bash-completion
            update_cache: yes
            cache_valid_time: 3600
            install_recommends: no
          become: yes
        - name: Check whether kubectl completion file exists
          stat:
            path: /etc/bash_completion.d/kubectl
          register: result
        - name: Create kubectl completion file
          command: /bin/bash -lc  "kubectl completion bash > /etc/bash_completion.d/kubectl"
          when: not result.stat.exists
          become: yes
    - name: Setup settings related to VPN
      import_tasks: openvpn.yml
