---
- hosts: devenv
  roles:
    - role: FGtatsuro.docker_toolbox
    - role: FGtatsuro.ssh_config
  tasks:
    - name: Create a workspace directory
      file:
        path: repos
        state: directory
    - name: Setup Golang environment
      import_tasks: golang.yml
    - name: Setup Github
      import_tasks: github.yml
