---
- hosts: devenv
  pre_tasks:
    - name: Set JP-sepecific settings
      import_tasks: jp.yml
  roles:
    - role: FGtatsuro.docker_toolbox
    - role: FGtatsuro.ssh_config
  tasks:
    - name: Create a workspace directory
      file:
        path: repos
        state: directory
    - name: Additional setup Python environment
      import_tasks: python.yml
    - name: Setup color settings
      import_tasks: color.yml
    - name: Setup Golang environment
      import_tasks: golang.yml
    - name: Setup Github
      import_tasks: github.yml
    - name: Setup vim
      import_tasks: vim.yml
    - name: Install peco
      apt:
        name: peco
        update_cache: yes
        cache_valid_time: 3600
        install_recommends: no
      become: yes
    - name: Install SQLite3 CLI
      apt:
        name: sqlite3
        update_cache: yes
        cache_valid_time: 3600
        install_recommends: no
      become: yes
- hosts: localhost
  roles:
    - role: FGtatsuro.tmux
  tasks:
    # TODO: Handle this task in tmux role.
    - name: Copy tmux settings
      copy:
        src: "../resources/tmux.conf"
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
    - name: Add profile settings to run tmux on terminal startup
      blockinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        block: |
          if [ $SHLVL = 1 ]; then
            tmux attach || tmux
          fi
        create: yes
