---
- hosts: devenv
  pre_tasks:
    - name: Set JP-sepecific settings
      import_tasks: jp.yml
  roles:
    - role: FGtatsuro.docker_toolbox
    - role: FGtatsuro.ssh_config
  tasks:
    - name: Create a workspace directory
      file:
        path: repos
        state: directory
    - name: Setup Golang environment
      import_tasks: golang.yml
    - name: Setup Github
      import_tasks: github.yml
    - name: Setup vim
      import_tasks: vim.yml
    - name: Install peco
      apt:
        name: peco
        update_cache: yes
        cache_valid_time: 3600
        install_recommends: no
      become: yes
- hosts: localhost
  roles:
    - role: FGtatsuro.tmux
